---
apiVersion: v1
kind: Service
metadata:
  name: customerdatadb
  labels:
    app: customerdatadb
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: customerdatadb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: customerdatadb
  labels:
    app: customerdatadb
spec:
  serviceName: customerdatadb
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: customerdatadb
  template:
    metadata:
      name: customerdatadb-postgresql
      labels:
        app: customerdatadb
    spec:
      securityContext:
        fsGroup: 26
        runAsUser: 26
      containers:
        - name: customerdatadb-postgresql
          image: quay.io/internaldatahub/postgresql-96-centos7:9.6
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: "postgres"
            - name: POSTGRESQL_USER
              value: "postgres"
            - name: POSTGRESQL_PASSWORD
              value: "postgres"
            - name: POSTGRESQL_DATABASE
              value: "customers"
            - name: PGDATA
              value: /var/lib/pgsql/data/pgdata

          ports:
            - name: postgresql
              containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 5432

            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: customerdatadb-data
              mountPath: /var/lib/pgsql/data
              subPath: pgdata
  volumeClaimTemplates:
    - metadata:
        name: customerdatadb-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
